[package]
name = "rust_graphics"
version = "0.1.0"
authors = ["durasel74 <diman174cheb@mail.ru>"]
edition = "2021"

[dependencies]
rand = "0.8.4"
image = "0.23.14"
cgmath = "0.18.0"
gl = "0.14"
glutin = "0.28.0"
