[package]
name = "rust_graphics"
version = "0.1.0"
authors = ["durasel74 <diman174cheb@mail.ru>"]
edition = "2021"

[dependencies]
cgmath = "0.18.0"
image = "0.23.14"
gl = "0.14"

[dependencies.sdl2]
version = "0.35"
features = ["bundled", "static-link"]
